#
# Copyright (c) 2012-2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

{{- define "prometheusHost" }}
{{- printf "prometheus-%s.%s" .Release.Namespace .Values.global.ingressDomain }}
{{- end }}

{{- define "grafanaHost" }}
{{- printf "grafana-%s.%s" .Release.Namespace .Values.global.ingressDomain }}
{{- end }}


{{ if or .Values.prometheus.deploy .Values.grafana.deploy }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: che-metrics-ingress
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.metrics.ingress.class }}"
    {{- range $key, $value := .Values.metrics.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
{{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
  {{- if .Values.prometheus.deploy }}
    - {{ template "prometheusHost" . }}
  {{- end }}
  {{- if .Values.grafana.deploy }}
    - {{ template "grafanaHost" . }}
  {{- end }}
    secretName: {{ .Values.global.tls.secretName }}
{{- end }}
{{- if .Values.prometheus.deploy }}
  rules:
  - host: {{ template "prometheusHost" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: che-prometheus-server
          servicePort: 80
{{- end }}
{{- if .Values.grafana.deploy }}
  - host: {{ template "grafanaHost" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: che-grafana
          servicePort: 80
{{- end }}

{{- end }}
