{{- if .Values.sonar-secrets.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sonarqube.fullname" . }}
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.sonar-secrets.bitbucketKey }}
  bitbucketKey: {{ .Values.sonar-secrets.bitbucketKey }}
{{- end }}
{{- if .Values.sonar-secrets.bitbucketSecret }}
  bitbucketSecret: {{ .Values.sonar-secrets.bitbucketSecret }}
{{- end }}
{{- if .Values.sonar-secrets.postgresql-password }}
  postgresql-password: {{ .Values.sonar-secrets.postgresql-password }}
{{- end }}
  {{ template "postgresql.secretPasswordKey" . }}: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
{{- end -}}
git