{{- if .Values.sonarSecrets.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sonarqube.fullname" . }}
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.sonarSecrets.bitbucketKey }}
  bitbucketKey: {{ .Values.sonarSecrets.bitbucketKey }}
{{- end }}
{{- if .Values.sonarSecrets.bitbucketSecret }}
  bitbucketSecret: {{ .Values.sonarSecrets.bitbucketSecret }}
{{- end }}
{{- if .Values.sonarSecrets.postgresqlPassword }}
  postgresql-password: {{ .Values.sonarSecrets.postgresqlPassword }}
{{- end }}
{{- end }}